### PR TITLE
Add Colab tutorial about using HFTA on top of a normal PyTorch model

### PR DESCRIPTION
**Pull request by eric-zheng**
Tested.

Check the entry point at this place on Readme.md:

Screenshot 2021-04-19 163903

@wangshangsam If you want to modify the sentences or examples, could you save a copy of that colab in your Google Drive and modify it there? And I can take the updated version. If it's a small change, please just let me know.

Thanks

### CODE REVIEW

**Review by wangshangsam — COMMENTED** [review]
~~Hmmm, I can't quite review this in GitHub PR. Could you share with me the link to your colab notebook and give me permission for adding comments? (top right corner -> Share -> add `samshang.wang@gmail.com` -> Change `Editor` to `Commentor` -> Send ) That might be easier.~~

Actually, I made a copy of it at https://colab.research.google.com/drive/1gSW6PpWAKfHI3GCxOmSrbBS5PFzh7HEl?usp=sharing (in our `MLSys21` Google drive folder). Let's take the review to there; I'll comment and you can edit in place. When it's good to go, you can make a copy of it and replace it with the version in this branch.

Also, I just promoted you to be the owner of that copy. Everyone else has commenter permission.

**Comment by eric-zheng** [comment]
I have updated the tutorial based on comments. Please take a look again. Thanks!

**Review by wangshangsam — CHANGES_REQUESTED** [review]
I left a few more comments in the colab.

I'm wondering if you would be able to run the code in colab and save the output to `docs/HFTA_PyTorch_Tutorial.ipynb`? It would be clearer if we have output alongside the text.

**Comment by eric-zheng** [comment]
I have updated the tutorial and tested. However, I couldn't find a way to save the output as it seems like colab doesn't have this option. But it's fast to run and reproduce. Can you take a look? I also marked you as an editor and could you directly edit it if you want to change anything? It's a bit hard to locate the text from comments (not as good as google docs...).

Thanks

**Review by wangshangsam — APPROVED** [review]
Saving the output can be turned on from `Runtime` -> `Change runtime type` -> Uncheck `Omit code cell output when saving this notebook`. I already turned it on.

I modified a few places, re-ran all the cells and saved the output. You can commit a copy of the current version into `eric/colab-tutorial`, then merge this PR.

**Comment by eric-zheng** [comment]
Thanks @wangshangsam, I have updated the file and merged the pull request. Close this branch for now.

**Pull request merged**
